version: '3.8'
services:

  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./DatabaseData/init.sql:/docker-entrypoint-initdb.d/init.sql
      
volumes:
  pg_data: